"""empty message

Revision ID: 30f3702ace01
Revises: 5c6f0c243668
Create Date: 2024-09-03 17:52:20.110656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f3702ace01'
down_revision = '5c6f0c243668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_notifications', schema=None) as batch_op:
        batch_op.drop_column('notification_sent')

    # ### end Alembic commands ###
