"""empty message

Revision ID: 342b423938d7
Revises: 844aba97c6cd
Create Date: 2024-09-01 22:24:29.255932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342b423938d7'
down_revision = '844aba97c6cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.drop_column('room_number')

    # ### end Alembic commands ###
